<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * chat_messages stores every message exchanged between
     * a user/guest and the chatbot. Each row is one message —
     * either from the user ('user') or the chatbot ('bot').
     *
     * This table serves two purposes:
     * 1. Lets registered users view and delete their chat history
     * 2. Maintains conversation context to pass to the LLM
     *    so it can give coherent follow-up responses
     */
    public function up(): void
    {
        Schema::create('chat_messages', function (Blueprint $table) {
            $table->id();

            // Links to a registered user — nullable because
            // guests won't have a user_id
            $table->foreignId('user_id')
                  ->nullable()
                  ->constrained()
                  ->onDelete('cascade');
                  // cascade: if user is deleted, their messages
                  // are also deleted automatically

            // Links to a guest session — nullable because
            // registered users won't have a session token
            $table->string('guest_session_token')->nullable();

            // 'user' = message sent by the student
            // 'bot'  = response generated by the chatbot
            // This is important for reconstructing conversation
            // history to send to the LLM as context
            $table->enum('role', ['user', 'bot']);

            // The actual message content
            // longText supports very long responses from the LLM
            $table->longText('message');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('chat_messages');
    }
};
